const customers = [
  {
    key: "1",
    school: "Indian School of Learning",
    place: "Jharia",
    year: "Since Inception",
  },
  {
    key: "2",
    school: "Indian School of Learning",
    place: "Sudamith",
    year: "Since Inception",
  },
  {
    key: "3",
    school: "Indian School of Learning",
    place: "Moonidh",
    year: "Since Inception",
  },
  {
    key: "4",
    school: "Indian School of Learning",
    place: "Bhuli",
    year: "Since Inception",
  },
  {
    key: "5",
    school: "Indian School of Learning",
    place: "Bokaro Thermal",
    year: "Since Inception",
  },
  {
    key: "6",
    school: "D.A.V. Public School",
    place: "Koyla Nagar",
    year: "Since Inception",
  },
  {
    key: "7",
    school: "D.A.V. Public School",
    place: "Alkusa",
    year: "33 years",
  },
  {
    key: "8",
    school: "D.A.V. Public School",
    place: "Moonidh",
    year: "33 years",
  },
  {
    key: "9",
    school: "D.A.V. Public School",
    place: "Kusunda",
    year: "30 years",
  },
  {
    key: "10",
    school: "D.A.V. Public School",
    place: "C.F.R.I.",
    year: "25 years",
  },
  {
    key: "11",
    school: "D.A.V. Public School",
    place: "Baniahir",
    year: "25 years",
  },
  {
    key: "12",
    school: "D.A.V. Public School",
    place: "Sindri",
    year: "Since Inception",
  },
  {
    key: "13",
    school: "D.A.V. Public School",
    place: "Baroda",
    year: "4 years",
  },
  {
    key: "14",
    school: "Tata D.A.V. School",
    place: "Jamadoba",
    year: "25 years",
  },
  { key: "15", school: "Tata D.A.V. School", place: "Sijua", year: "25 years" },
  {
    key: "16",
    school: "Delhi Public School",
    place: "Dhanbad",
    year: "16 years",
  },
  { key: "17", school: "Rajkamal S.V.M.", place: "Dhansar", year: "10 years" },
  {
    key: "18",
    school: "Saraswati Vidya Mandir",
    place: "Bhuli",
    year: "8 years",
  },
  {
    key: "19",
    school: "Saraswati Vidya Mandir",
    place: "Shyamdih",
    year: "2 years",
  },
  {
    key: "20",
    school: "Kids Garden Secondary School",
    place: "Jharia",
    year: "Since Inception",
  },
  {
    key: "21",
    school: "Kids Garden",
    place: "Dhanbad",
    year: "Since Inception",
  },
  {
    key: "22",
    school: "Lions Public School",
    place: "Sindri",
    year: "Since Inception",
  },
  {
    key: "23",
    school: "JNM Sr. Sec. School",
    place: "Diwadih",
    year: "35 years",
  },
  {
    key: "24",
    school: "Doon Public School",
    place: "Dhanbad",
    year: "20 years",
  },
  {
    key: "25",
    school: "Holy Mother School",
    place: "Katras",
    year: "Since Inception",
  },
  {
    key: "26",
    school: "Dhabad City School",
    place: "Bhuli",
    year: "Since Inception",
  },
  {
    key: "27",
    school: "M.M. Vidyapeeth",
    place: "Dhanbad",
    year: "Since Inception",
  },
  {
    key: "28",
    school: "St. Thomas School",
    place: "Topchanchi",
    year: "10 years",
  },
  {
    key: "29",
    school: "Fagu Mahato School (JAC)",
    place: "Kapuria",
    year: "15 years",
  },
  {
    key: "30",
    school: "Jharkhand Public School",
    place: "Balipur - Sindri",
    year: "Since Inception",
  },
  {
    key: "31",
    school: "S.S.S.S.S. Vidyapeeth",
    place: "Dhanbad",
    year: "Since Inception",
  },
  {
    key: "32",
    school: "Dhanbad Public School",
    place: "Hirak Road, Dhanbad",
    year: "5 years",
  },
  {
    key: "33",
    school: "Bud's Garden School",
    place: "Rajganj",
    year: "4 years",
  },
  { key: "34", school: "Manfort Academy", place: "Rajganj", year: "3 years" },
  {
    key: "35",
    school: "Symbiosis Public School",
    place: "Barwadda",
    year: "7 years",
  },
  {
    key: "36",
    school: "Balika Vidya Mandir",
    place: "Jharia",
    year: "7 years",
  },
  {
    key: "37",
    school: "Shyama Pd. Mukherji Inter College",
    place: "Sindri",
    year: "Since Inception",
  },
  {
    key: "38",
    school: "P.K. Roy Memorial College",
    place: "Dhanbad",
    year: "20 years",
  },
  {
    key: "39",
    school: "Jawahar Navodaya Vidyalaya",
    place: "Dhanbad",
    year: "17 years",
  },
  {
    key: "40",
    school: "Kasturba Gandhi Vidyalaya",
    place: "Dhanbad",
    year: "10 years",
  },
];

export default customers;
