const products = [
  {
    key: "1",
    name: "Beaker",
    category: "Glassware",
    info: [
      { key: "1", size: "50ml", price: "65.00", quantity: "1" },
      { key: "2", size: "100ml", price: "80.00", quantity: "1" },
      { key: "3", size: "150ml", price: "95.00", quantity: "1" },
      { key: "4", size: "250ml", price: "115.00", quantity: "1" },
      { key: "5", size: "500ml", price: "140.00", quantity: "1" },
    ],
  },
  {
    key: "2",
    name: "Conical Flask",
    category: "Glassware",
    info: [
      { key: "1", size: "150ml", price: "105.00", quantity: "1" },
      { key: "2", size: "250ml", price: "126.00", quantity: "1" },
    ],
  },
  {
    key: "3",
    name: "Round Bottom Flask",
    category: "Glassware",
    info: [{ key: "1", size: "250ml", price: "140.00", quantity: "1" }],
  },
  {
    key: "4",
    name: "Flat Bottom Flask",
    category: "Glassware",
    info: [{ key: "1", size: "250ml", price: "140.00", quantity: "1" }],
  },
  {
    key: "5",
    name: "Distillation Flask",
    category: "Glassware",
    info: [{ key: "1", size: "250ml", price: "230.00", quantity: "1" }],
  },
  {
    key: "6",
    name: "Measuring Flask",
    category: "Glassware",
    info: [
      { key: "1", size: "1L", price: "430.00", quantity: "1" },
      { key: "2", size: "250ml", price: "220.00", quantity: "1" },
    ],
  },
  {
    key: "7",
    name: "Measuring Cylinder",
    category: "Glassware",
    info: [
      { key: "1", size: "100ml", price: "210.00", quantity: "1" },
      { key: "2", size: "250ml", price: "370.00", quantity: "1" },
    ],
  },
  {
    key: "8",
    name: "Burette Tafflon Screw Type",
    category: "Glassware",
    info: [{ key: "1", price: "230.00", quantity: "1" }],
  },
  {
    key: "9",
    name: "Burette Pinch Cock System",
    category: "Glassware",
    info: [{ key: "1", price: "95.00", quantity: "1" }],
  },
  {
    key: "10",
    name: "Pipette",
    category: "Glassware",
    info: [
      { key: "1", size: "10ml", price: "85.00", quantity: "1" },
      { key: "2", size: "5ml", price: "85.00", quantity: "1" },
    ],
  },
  {
    key: "11",
    name: "Graduated Pipette",
    category: "Glassware",
    info: [{ key: "1", size: "10ml", price: "130.00", quantity: "1" }],
  },
  {
    key: "12",
    name: "Woulfs Bottle",
    category: "Glassware",
    info: [{ key: "1", price: "330.00", quantity: "1" }],
  },
  {
    key: "13",
    name: "Conical Funnel",
    category: "Glassware",
    info: [{ key: "1", price: "65.00", quantity: "1" }],
  },
  {
    key: "14",
    name: "Thistle Funnel",
    category: "Glassware",
    info: [{ key: "1", price: "50.00", quantity: "1" }],
  },
  {
    key: "15",
    name: "Separating Funnel",
    category: "Glassware",
    info: [{ key: "1", price: "225.00", quantity: "1" }],
  },
  {
    key: "16",
    name: 'Petri Dish 4"',
    category: "Glassware",
    info: [{ key: "1", price: "145.00", quantity: "1" }],
  },
  {
    key: "17",
    name: "Specific Gravity Bottle",
    category: "Glassware",
    info: [{ key: "1", price: "95.00", quantity: "1" }],
  },
  {
    key: "18",
    name: "Ganongs Potometer",
    category: "Glassware",
    info: [{ key: "1", price: "580.00", quantity: "1" }],
  },
  {
    key: "19",
    name: "Farmers Potometer",
    category: "Glassware",
    info: [{ key: "1", price: "580.00", quantity: "1" }],
  },
  {
    key: "20",
    name: "Wilmot Bubler",
    category: "Glassware",
    info: [{ key: "1", price: "580.00", quantity: "1" }],
  },
  {
    key: "21",
    name: "Reagent Bottle",
    category: "Glassware",
    info: [
      { key: "1", size: "60ml", price: "95.00", quantity: "1" },
      { key: "2", size: "125ml", price: "155.00", quantity: "1" },
      { key: "3", size: "250ml", price: "190.00", quantity: "1" },
    ],
  },
  {
    key: "22",
    name: "Dropper",
    category: "Glassware",
    info: [{ key: "1", price: "25.00", quantity: "1" }],
  },
  {
    key: "23",
    name: "Test Tube",
    category: "Glassware",
    info: [
      { key: "1", size: "15x125", price: "95.00", quantity: "100" },
      { key: "2", size: "25x150", price: "780.00", quantity: "50" },
    ],
  },
  {
    key: "24",
    name: "Bend Glass",
    category: "Glassware",
    info: [{ key: "1", price: "65.00", quantity: "Set of 2" }],
  },
  {
    key: "25",
    name: "Plain Slide",
    category: "Glassware",
    info: [{ key: "1", price: "105.00", quantity: "pkt." }],
  },
  {
    key: "26",
    name: "Cover Glass",
    category: "Glassware",
    info: [{ key: "1", price: "35.00", quantity: "pkt." }],
  },
  {
    key: "27",
    name: "Reagent Bottle",
    category: "Neutral Glass",
    info: [{ key: "1", price: "660.00", quantity: "12" }],
  },
  {
    key: "28",
    name: "Dropping Bottle",
    category: "Neutral Glass",
    info: [{ key: "1", price: "800.00", quantity: "12" }],
  },
  {
    key: "29",
    name: "Watch Glass",
    category: "Neutral Glass",
    info: [{ key: "1", price: "200.00", quantity: "12" }],
  },
  {
    key: "30",
    name: "Glass Stirrer",
    category: "Neutral Glass",
    info: [{ key: "1", price: "135.00", quantity: "12" }],
  },
  {
    key: "31",
    name: "Dropper Big",
    category: "Neutral Glass",
    info: [{ key: "1", price: "265.00", quantity: "12" }],
  },
  {
    key: "32",
    name: "Glass Tube",
    category: "Neutral Glass",
    info: [{ key: "1", price: "135.00", quantity: "12" }],
  },
  {
    key: "33",
    name: "Pipette",
    category: "Neutral Glass",
    info: [{ key: "1", price: "70.00", quantity: "1" }],
  },
  {
    key: "34",
    name: "Chemical Balance",
    category: "Chemistry",
    info: [{ key: "1", price: "2785.00", quantity: "1" }],
  },
  {
    key: "35",
    name: "Analytical Wt. Box",
    category: "Chemistry",
    info: [{ key: "1", price: "995.00", quantity: "1" }],
  },
  {
    key: "36",
    name: "Stand Clamp Set Heavy",
    category: "Chemistry",
    info: [{ key: "1", price: "465.00", quantity: "1" }],
  },
  {
    key: "37",
    name: "Surette Clamp",
    category: "Chemistry",
    info: [{ key: "1", price: "135.00", quantity: "1" }],
  },
  {
    key: "38",
    name: "Tropped Stand",
    category: "Chemistry",
    info: [{ key: "1", price: "99.00", quantity: "1" }],
  },
  {
    key: "39",
    name: "Wire Gauge",
    category: "Chemistry",
    info: [{ key: "1", price: "35.00", quantity: "1" }],
  },
  {
    key: "40",
    name: "Sprint Lamp",
    category: "Chemistry",
    info: [{ key: "1", price: "80.00", quantity: "1" }],
  },
  {
    key: "41",
    name: "Blow Pipe",
    category: "Chemistry",
    info: [{ key: "1", price: "55.00", quantity: "1" }],
  },
  {
    key: "42",
    name: "Test Tube Holder",
    category: "Chemistry",
    info: [{ key: "1", price: "35.00", quantity: "1" }],
  },
  {
    key: "43",
    name: "Test Tube Brush",
    category: "Chemistry",
    info: [{ key: "1", price: "130.00", quantity: "12" }],
  },
  {
    key: "44",
    name: "Test Tube Stand",
    category: "Chemistry",
    info: [{ key: "1", price: "90.00", quantity: "1" }],
  },
  {
    key: "45",
    name: "Wash Bottle",
    category: "Chemistry",
    info: [{ key: "1", price: "85.00", quantity: "1" }],
  },
  {
    key: "46",
    name: "Kipps Apparatus",
    category: "Chemistry",
    info: [{ key: "1", price: "1300.00", quantity: "1" }],
  },
  {
    key: "47",
    name: "Water Trough",
    category: "Chemistry",
    info: [{ key: "1", price: "135.00", quantity: "1" }],
  },
  {
    key: "48",
    name: "Gas Jar With Lid",
    category: "Chemistry",
    info: [{ key: "1", price: "120.00", quantity: "Pair" }],
  },
  {
    key: "49",
    name: "Burette",
    category: "Chemistry",
    info: [{ key: "1", price: "395.00", quantity: "1" }],
  },
  {
    key: "50",
    name: "Pipette Stand",
    category: "Chemistry",
    info: [{ key: "1", size: "Circular", price: "605.00", quantity: "1" }],
  },
  {
    key: "51",
    name: "Conical Funnel",
    category: "Chemistry",
    info: [{ key: "1", price: "16.00", quantity: "1" }],
  },
  {
    key: "52",
    name: "Hand Glove",
    category: "Chemistry",
    info: [{ key: "1", price: "95.00", quantity: "Pair" }],
  },
  {
    key: "53",
    name: "Triangular File Handle",
    category: "Chemistry",
    info: [{ key: "1", price: "105.00", quantity: "1" }],
  },
  {
    key: "54",
    name: "Spatula",
    category: "Chemistry",
    info: [{ key: "1", price: "30.00", quantity: "1" }],
  },
  {
    key: "55",
    name: "China Dish Basin",
    category: "Chemistry",
    info: [{ key: "1", price: "70.00", quantity: "1" }],
  },
  {
    key: "56",
    name: "Morter and Peastle",
    category: "Chemistry",
    info: [{ key: "1", price: "160.00", quantity: "1" }],
  },
  {
    key: "57",
    name: "Bee Hive Self",
    category: "Chemistry",
    info: [{ key: "1", price: "80.00", quantity: "1" }],
  },
  {
    key: "58",
    name: "Copper Water Bath",
    category: "Chemistry",
    info: [{ key: "1", price: "505.00", quantity: "1" }],
  },
  {
    key: "59",
    name: "Atomic Model",
    category: "Chemistry",
    info: [
      { key: "1", size: "Big", price: "765.00", quantity: "1" },
      { key: "2", size: "Junior", price: "305.00", quantity: "1" },
    ],
  },
  {
    key: "60",
    name: "Centrifuge Machine Handling Table Top",
    category: "Chemistry",
    info: [{ key: "1", price: "1050.00", quantity: "1" }],
  },
  {
    key: "61",
    name: "Periodic Table",
    category: "Chemistry",
    info: [{ key: "1", size: "100x70", price: "155.00", quantity: "1" }],
  },
  {
    key: "62",
    name: "Valancy Chart",
    category: "Chemistry",
    info: [{ key: "1", size: "90x60", price: "195.00", quantity: "1" }],
  },
  {
    key: "63",
    name: "Chemistry Chart",
    category: "Chemistry",
    info: [{ key: "1", size: "90x60", price: "195.00", quantity: "1" }],
  },
  {
    key: "64",
    name: "Oven",
    category: "Chemistry",
    info: [{ key: "1", size: "12x12x12", price: "15500.00", quantity: "1" }],
  },
  {
    key: "65",
    name: "Centrifuge Machine",
    category: "Chemistry",
    info: [{ key: "1", price: "4500.00", quantity: "1" }],
  },
  {
    key: "66",
    name: "Magnetic Stirrer",
    category: "Chemistry",
    info: [{ key: "1", price: "3800.00", quantity: "1" }],
  },
  {
    key: "67",
    name: "Hitting Mental",
    category: "Chemistry",
    info: [{ key: "1", price: "2750.00", quantity: "1" }],
  },
  {
    key: "68",
    name: "Micrscope",
    category: "Biology",
    info: [
      { key: "1", size: "Medical", price: "6950.00", quantity: "1" },
      { key: "2", size: "Jr. Medical", price: "6100.00", quantity: "1" },
      { key: "3", size: "Standard", price: "5800.00", quantity: "1" },
      { key: "4", size: "Compound", price: "5050.00", quantity: "1" },
      { key: "5", size: "General", price: "4570.00", quantity: "1" },
    ],
  },
  {
    key: "69",
    name: "Microscope Single Nose",
    category: "Biology",
    info: [{ key: "1", price: "2575.00", quantity: "1" }],
  },
  {
    key: "70",
    name: "Dissecting Microscope",
    category: "Biology",
    info: [{ key: "1", price: "1790.00", quantity: "1" }],
  },
  {
    key: "71",
    name: "Bull Eye Microscope",
    category: "Biology",
    info: [{ key: "1", price: "2890.00", quantity: "1" }],
  },
  {
    key: "72",
    name: "Double Demonstration Eye Piece",
    category: "Biology",
    info: [{ key: "1", price: "1850.00", quantity: "1" }],
  },
  {
    key: "73",
    name: "Pointer Eye Piece",
    category: "Biology",
    info: [{ key: "1", price: "505.00", quantity: "1" }],
  },
  {
    key: "74",
    name: "Microscope Lens",
    category: "Biology",
    info: [{ key: "1", price: "1470.00", quantity: "Set of 3" }],
  },
  {
    key: "75",
    name: "Lense for Dissecting Microscope",
    category: "Biology",
    info: [{ key: "1", price: "370.00", quantity: "1" }],
  },
  {
    key: "76",
    name: "Mechanical Stage",
    category: "Biology",
    info: [{ key: "1", price: "1160.00", quantity: "1" }],
  },
  {
    key: "77",
    name: "Gnifying Hand Lens",
    category: "Biology",
    info: [{ key: "1", price: "220.00", quantity: "1" }],
  },
  {
    key: "78",
    name: "Dissecting Set in Bag",
    category: "Biology",
    info: [{ key: "1", price: "475.00", quantity: "1" }],
  },
  {
    key: "79",
    name: "Dissecting Tray with Wax",
    category: "Biology",
    info: [{ key: "1", price: "350.00", quantity: "1" }],
  },
  {
    key: "80",
    name: "Dissecting Tray without Wax",
    category: "Biology",
    info: [{ key: "1", price: "295.00", quantity: "1" }],
  },
  {
    key: "81",
    name: "Wax",
    category: "Biology",
    info: [{ key: "1", price: "270.00", quantity: "1 Kg" }],
  },
  {
    key: "82",
    name: "Dropping Bottle Tray Wooden",
    category: "Biology",
    info: [{ key: "1", price: "190.00", quantity: "1" }],
  },
  {
    key: "83",
    name: "Centrifuge Machine (Hand Driven table Top)",
    category: "Biology",
    info: [{ key: "1", price: "1050.00", quantity: "1" }],
  },
  {
    key: "84",
    name: "Centrifuge Machine(Electic)",
    category: "Biology",
    info: [{ key: "1", price: "4420.00", quantity: "1" }],
  },
  {
    key: "85",
    name: "Insulator",
    category: "Biology",
    info: [{ key: "1", size: "12x12x12", price: "15500.00", quantity: "1" }],
  },
  {
    key: "86",
    name: "Heating Mental",
    category: "Biology",
    info: [{ key: "1", price: "2750.00", quantity: "1" }],
  },
  {
    key: "87",
    name: "Museum Specimen",
    category: "Biology",
    info: [{ key: "1", price: "195.00", quantity: "1" }],
  },
  {
    key: "88",
    name: "Permanent Slide",
    category: "Biology",
    info: [
      { key: "1", size: "Common", price: "30.00", quantity: "1" },
      { key: "2", size: "Rear", price: "120", quantity: "1" },
    ],
  },
  {
    key: "89",
    name: "Slide Box",
    category: "Biology",
    info: [
      { key: "1", size: "25 Slides", price: "85.00", quantity: "1" },
      { key: "2", size: "50 Slides", price: "160.00", quantity: "1" },
    ],
  },
  {
    key: "90",
    name: "Physical Balance",
    category: "Physics X",
    info: [{ key: "1", price: "2260.00", quantity: "1" }],
  },
  {
    key: "91",
    name: "Physical Wt. Box",
    category: "Physics X",
    info: [{ key: "1", price: "580.00", quantity: "1" }],
  },
  {
    key: "92",
    name: "Spring Balance Tubular (Acrylic)",
    category: "Physics X",
    info: [{ key: "1", price: "150.00", quantity: "1" }],
  },
  {
    key: "93",
    name: "Pan for Spring Balance",
    category: "Physics X",
    info: [{ key: "1", price: "55.00", quantity: "1" }],
  },
  {
    key: "94",
    name: "Archmedies Bucket",
    category: "Physics X",
    info: [{ key: "1", price: "220.00", quantity: "1" }],
  },
  {
    key: "95",
    name: "Overflow Vessle",
    category: "Physics X",
    info: [{ key: "1", price: "250.00", quantity: "1" }],
  },
  {
    key: "96",
    name: "Measuring Cylinder",
    category: "Physics X",
    info: [
      { key: "1", size: "100ml", price: "75.00", quantity: "1" },
      { key: "2", size: "250ml", price: "105.00", quantity: "1" },
    ],
  },
  {
    key: "97",
    name: "Vernier Calliper",
    category: "Physics X",
    info: [{ key: "1", price: "430.00", quantity: "1" }],
  },
  {
    key: "98",
    name: "Screw Gauge",
    category: "Physics X",
    info: [{ key: "1", price: "370.00", quantity: "1" }],
  },
  {
    key: "99",
    name: "Spherometer Double Disc",
    category: "Physics X",
    info: [{ key: "1", price: "370.00", quantity: "1" }],
  },
  {
    key: "100",
    name: "Pendulum Bob",
    category: "Physics X",
    info: [{ key: "1", price: "90.00", quantity: "1" }],
  },
  {
    key: "101",
    name: "Brass Cylinder",
    category: "Physics X",
    info: [{ key: "1", price: "100.00", quantity: "1" }],
  },
  {
    key: "102",
    name: "Stop Clock",
    category: "Physics X",
    info: [{ key: "1", price: "790.00", quantity: "1" }],
  },
  {
    key: "103",
    name: "Full meter Scale",
    category: "Physics X",
    info: [{ key: "1", price: "155.00", quantity: "1" }],
  },
  {
    key: "104",
    name: "Half Meter Scale",
    category: "Physics X",
    info: [{ key: "1", price: "80.00", quantity: "1" }],
  },
  {
    key: "105",
    name: "Drawing Board",
    category: "Physics X",
    info: [{ key: "1", size: "12x18", price: "360.00", quantity: "1" }],
  },
  {
    key: "106",
    name: "Drawing Pin",
    category: "Physics X",
    info: [{ key: "1", price: "45.00", quantity: "1" }],
  },
  {
    key: "107",
    name: "Incline Plain",
    category: "Physics X",
    info: [{ key: "1", price: "895.00", quantity: "1" }],
  },
  {
    key: "108",
    name: "Friction Table",
    category: "Physics X",
    info: [{ key: "1", price: "500.00", quantity: "1" }],
  },
  {
    key: "109",
    name: "Paral Togram of Forces App.",
    category: "Physics X",
    info: [{ key: "1", price: "895.00", quantity: "1" }],
  },
  {
    key: "110",
    name: "Sprint Level",
    category: "Physics X",
    info: [{ key: "1", price: "55.00", quantity: "1" }],
  },
  {
    key: "111",
    name: "Helical Spring",
    category: "Physics X",
    info: [{ key: "1", price: "130.00", quantity: "1" }],
  },
  {
    key: "112",
    name: "Newton's Colour Disc",
    category: "Physics X",
    info: [{ key: "1", price: "190.00", quantity: "1" }],
  },
  {
    key: "113",
    name: "Glass Slab",
    category: "Physics X",
    info: [{ key: "1", price: "115.00", quantity: "1" }],
  },
  {
    key: "114",
    name: "Glass Prism",
    category: "Physics X",
    info: [{ key: "1", price: "105.00", quantity: "1" }],
  },
  {
    key: "115",
    name: "Plain Mirror",
    category: "Physics X",
    info: [{ key: "1", price: "35.00", quantity: "1" }],
  },
  {
    key: "116",
    name: "Concave Mirror",
    category: "Physics X",
    info: [{ key: "1", price: "70.00", quantity: "1" }],
  },
  {
    key: "117",
    name: "Convex Mirror",
    category: "Physics X",
    info: [{ key: "1", price: "70.00", quantity: "1" }],
  },
  {
    key: "118",
    name: "Universal Lens Stand",
    category: "Physics X",
    info: [{ key: "1", price: "200.00", quantity: "1" }],
  },
  {
    key: "119",
    name: "Universal Pin Stand",
    category: "Physics X",
    info: [{ key: "1", price: "235.00", quantity: "1" }],
  },
  {
    key: "120",
    name: "OPtical Bench",
    category: "Physics X",
    info: [{ key: "1", size: "1.5 mtr", price: "5900.00", quantity: "1" }],
  },
  {
    key: "121",
    name: "Thermometer Mercury",
    category: "Physics X",
    info: [{ key: "1", price: "185.00", quantity: "1" }],
  },
  {
    key: "122",
    name: "Thermometer Alcohol",
    category: "Physics X",
    info: [{ key: "1", price: "115.00", quantity: "1" }],
  },
  {
    key: "123",
    name: "Digital Thermometer",
    category: "Physics X",
    info: [{ key: "1", price: "720.00", quantity: "1" }],
  },
  {
    key: "124",
    name: "Transmission of Head App.",
    category: "Physics X",
    info: [{ key: "1", price: "160.00", quantity: "1" }],
  },
  {
    key: "125",
    name: "Ring and Ball App.",
    category: "Physics X",
    info: [{ key: "1", price: "235.00", quantity: "1" }],
  },
  {
    key: "126",
    name: "Bimetallic Stripe",
    category: "Physics X",
    info: [{ key: "1", price: "190.00", quantity: "1" }],
  },
  {
    key: "127",
    name: 'Bar Magnet 2"',
    category: "Physics X",
    info: [{ key: "1", price: "150.00", quantity: "Pair" }],
  },
  {
    key: "128",
    name: 'Bar Magnet 3"',
    category: "Physics X",
    info: [{ key: "1", price: "220.00", quantity: "Pair" }],
  },
  {
    key: "129",
    name: 'Horse Shoe Magnet 4"',
    category: "Physics X",
    info: [{ key: "1", price: "235.00", quantity: "1" }],
  },
  {
    key: "130",
    name: "Compass Box",
    category: "Physics X",
    info: [{ key: "1", price: "430.00", quantity: "1" }],
  },
  {
    key: "131",
    name: 'Magnetic Compass 4"',
    category: "Physics X",
    info: [{ key: "1", price: "430.00", quantity: "1" }],
  },
  {
    key: "132",
    name: 'Magnetic Compass 2"',
    category: "Physics X",
    info: [{ key: "1", price: "45.00", quantity: "1" }],
  },
  {
    key: "134",
    name: "Magnetic Compass BSG",
    category: "Physics X",
    info: [{ key: "1", price: "30.00", quantity: "1" }],
  },
  {
    key: "135",
    name: "Resistance Box Mangnin Coil",
    category: "Physics X",
    info: [{ key: "1", price: "1935.00", quantity: "1" }],
  },
  {
    key: "136",
    name: 'Rheostat 8"',
    category: "Physics X",
    info: [{ key: "1", price: "995.00", quantity: "1" }],
  },
  {
    key: "137",
    name: "Ammeter",
    category: "Physics X",
    info: [{ key: "1", price: "360.00", quantity: "1" }],
  },
  {
    key: "138",
    name: "Voltmeter",
    category: "Physics X",
    info: [{ key: "1", price: "360.00", quantity: "1" }],
  },
  {
    key: "139",
    name: "Galvanometer",
    category: "Physics X",
    info: [{ key: "1", price: "360.00", quantity: "1" }],
  },
  {
    key: "140",
    name: "Battery Eliminator",
    category: "Physics X",
    info: [{ key: "1", price: "1395.00", quantity: "1" }],
  },
  {
    key: "141",
    name: "Ohm's Law App.",
    category: "Physics X",
    info: [{ key: "1", price: "1525.00", quantity: "1" }],
  },
  {
    key: "142",
    name: "Single Resistance",
    category: "Physics X",
    info: [{ key: "1", price: "55.00", quantity: "1" }],
  },
  {
    key: "143",
    name: "Connecting ire SCC",
    category: "Physics X",
    info: [
      { key: "1", size: "100gr Coil", price: "185.00", quantity: "1" },
      { key: "2", size: "500gr Coil", price: "840.00", quantity: "1" },
    ],
  },
  {
    key: "144",
    name: "Plug Key one way",
    category: "Physics X",
    info: [{ key: "1", price: "115.00", quantity: "1" }],
  },
  {
    key: "145",
    name: "Tapping Key",
    category: "Physics X",
    info: [{ key: "1", price: "80.00", quantity: "1" }],
  },
  {
    key: "146",
    name: "Copper Plate - Zinc Plate Set",
    category: "Physics X",
    info: [{ key: "1", price: "190.00", quantity: "1" }],
  },
  {
    key: "147",
    name: "Solar Cell App.",
    category: "Physics X",
    info: [{ key: "1", price: "1260.00", quantity: "1" }],
  },
  {
    key: "148",
    name: "Stand Clamp Set Heavy",
    category: "Physics X",
    info: [{ key: "1", price: "470.00", quantity: "1" }],
  },
  {
    key: "149",
    name: "Laser Torch",
    category: "Physics X",
    info: [{ key: "1", price: "410.00", quantity: "1" }],
  },
  {
    key: "150",
    name: "Physics Chart",
    category: "Physics X",
    info: [{ key: "1", price: "195.00", quantity: "1" }],
  },
];
export default products;
