const products = [
  {
    key: "1",
    name: "Beaker",
    category: "Glassware",
    info: [
      { key: "1", size: "50ml", price: "65.00", quantity: "1" },
      { key: "2", size: "100ml", price: "80.00", quantity: "1" },
      { key: "3", size: "150ml", price: "95.00", quantity: "1" },
      { key: "4", size: "250ml", price: "115.00", quantity: "1" },
      { key: "5", size: "500ml", price: "140.00", quantity: "1" },
    ],
  },
  {
    key: "2",
    name: "Conical Flask",
    category: "Glassware",
    info: [
      { key: "1", size: "150ml", price: "105.00", quantity: "1" },
      { key: "2", size: "250ml", price: "126.00", quantity: "1" },
    ],
  },
  {
    key: "3",
    name: "Round Bottom Flask",
    category: "Glassware",
    info: [{ key: "1", size: "250ml", price: "140.00", quantity: "1" }],
  },
  {
    key: "4",
    name: "Flat Bottom Flask",
    category: "Glassware",
    info: [{ key: "1", size: "250ml", price: "140.00", quantity: "1" }],
  },
  {
    key: "5",
    name: "Distillation Flask",
    category: "Glassware",
    info: [{ key: "1", size: "250ml", price: "230.00", quantity: "1" }],
  },
  {
    key: "6",
    name: "Measuring Flask",
    category: "Glassware",
    info: [
      { key: "1", size: "1L", price: "430.00", quantity: "1" },
      { key: "2", size: "250ml", price: "220.00", quantity: "1" },
    ],
  },
  {
    key: "7",
    name: "Measuring Cylinder",
    category: "Glassware",
    info: [
      { key: "1", size: "100ml", price: "210.00", quantity: "1" },
      { key: "2", size: "250ml", price: "370.00", quantity: "1" },
    ],
  },
  {
    key: "8",
    name: "Burette Tafflon Screw Type",
    category: "Glassware",
    info: [{ key: "1", price: "230.00", quantity: "1" }],
  },
  {
    key: "9",
    name: "Burette Pinch Cock System",
    category: "Glassware",
    info: [{ key: "1", price: "95.00", quantity: "1" }],
  },
  {
    key: "10",
    name: "Pipette",
    category: "Glassware",
    info: [
      { key: "1", size: "10ml", price: "85.00", quantity: "1" },
      { key: "2", size: "5ml", price: "85.00", quantity: "1" },
    ],
  },
  {
    key: "11",
    name: "Graduated Pipette",
    category: "Glassware",
    info: [{ key: "1", size: "10ml", price: "130.00", quantity: "1" }],
  },
  {
    key: "12",
    name: "Woulfs Bottle",
    category: "Glassware",
    info: [{ key: "1", price: "330.00", quantity: "1" }],
  },
  {
    key: "13",
    name: "Conical Funnel",
    category: "Glassware",
    info: [{ key: "1", price: "65.00", quantity: "1" }],
  },
  {
    key: "14",
    name: "Thistle Funnel",
    category: "Glassware",
    info: [{ key: "1", price: "50.00", quantity: "1" }],
  },
  {
    key: "15",
    name: "Separating Funnel",
    category: "Glassware",
    info: [{ key: "1", price: "225.00", quantity: "1" }],
  },
  {
    key: "16",
    name: 'Petri Dish 4"',
    category: "Glassware",
    info: [{ key: "1", price: "145.00", quantity: "1" }],
  },
  {
    key: "17",
    name: "Specific Gravity Bottle",
    category: "Glassware",
    info: [{ key: "1", price: "95.00", quantity: "1" }],
  },
  {
    key: "18",
    name: "Ganongs Potometer",
    category: "Glassware",
    info: [{ key: "1", price: "580.00", quantity: "1" }],
  },
  {
    key: "19",
    name: "Farmers Potometer",
    category: "Glassware",
    info: [{ key: "1", price: "580.00", quantity: "1" }],
  },
  {
    key: "20",
    name: "Wilmot Bubler",
    category: "Glassware",
    info: [{ key: "1", price: "580.00", quantity: "1" }],
  },
  {
    key: "21",
    name: "Reagent Bottle",
    category: "Glassware",
    info: [
      { key: "1", size: "60ml", price: "95.00", quantity: "1" },
      { key: "2", size: "125ml", price: "155.00", quantity: "1" },
      { key: "3", size: "250ml", price: "190.00", quantity: "1" },
    ],
  },
  {
    key: "22",
    name: "Dropper",
    category: "Glassware",
    info: [{ key: "1", price: "25.00", quantity: "1" }],
  },
  {
    key: "23",
    name: "Test Tube",
    category: "Glassware",
    info: [
      { key: "1", size: "15x125", price: "95.00", quantity: "100" },
      { key: "2", size: "25x150", price: "780.00", quantity: "50" },
    ],
  },
  {
    key: "24",
    name: "Bend Glass",
    category: "Glassware",
    info: [{ key: "1", price: "65.00", quantity: "Set of 2" }],
  },
  {
    key: "25",
    name: "Plain Slide",
    category: "Glassware",
    info: [{ key: "1", price: "105.00", quantity: "pkt." }],
  },
  {
    key: "26",
    name: "Cover Glass",
    category: "Glassware",
    info: [{ key: "1", price: "35.00", quantity: "pkt." }],
  },
  {
    key: "27",
    name: "Reagent Bottle",
    category: "Neutral Glass",
    info: [{ key: "1", price: "660.00", quantity: "12" }],
  },
  {
    key: "28",
    name: "Dropping Bottle",
    category: "Neutral Glass",
    info: [{ key: "1", price: "800.00", quantity: "12" }],
  },
  {
    key: "29",
    name: "Watch Glass",
    category: "Neutral Glass",
    info: [{ key: "1", price: "200.00", quantity: "12" }],
  },
  {
    key: "30",
    name: "Glass Stirrer",
    category: "Neutral Glass",
    info: [{ key: "1", price: "135.00", quantity: "12" }],
  },
  {
    key: "31",
    name: "Dropper Big",
    category: "Neutral Glass",
    info: [{ key: "1", price: "265.00", quantity: "12" }],
  },
  {
    key: "32",
    name: "Glass Tube",
    category: "Neutral Glass",
    info: [{ key: "1", price: "135.00", quantity: "12" }],
  },
  {
    key: "33",
    name: "Pipette",
    category: "Neutral Glass",
    info: [{ key: "1", price: "70.00", quantity: "1" }],
  },
  {
    key: "34",
    name: "Chemical Balance",
    category: "Chemistry",
    info: [{ key: "1", price: "2785.00", quantity: "1" }],
  },
  {
    key: "35",
    name: "Analytical Wt. Box",
    category: "Chemistry",
    info: [{ key: "1", price: "995.00", quantity: "1" }],
  },
  {
    key: "36",
    name: "Stand Clamp Set Heavy",
    category: "Chemistry",
    info: [{ key: "1", price: "465.00", quantity: "1" }],
  },
  {
    key: "37",
    name: "Surette Clamp",
    category: "Chemistry",
    info: [{ key: "1", price: "135.00", quantity: "1" }],
  },
  {
    key: "38",
    name: "Tropped Stand",
    category: "Chemistry",
    info: [{ key: "1", price: "99.00", quantity: "1" }],
  },
  {
    key: "39",
    name: "Wire Gauge",
    category: "Chemistry",
    info: [{ key: "1", price: "35.00", quantity: "1" }],
  },
  {
    key: "40",
    name: "Sprint Lamp",
    category: "Chemistry",
    info: [{ key: "1", price: "80.00", quantity: "1" }],
  },
  {
    key: "41",
    name: "Blow Pipe",
    category: "Chemistry",
    info: [{ key: "1", price: "55.00", quantity: "1" }],
  },
  {
    key: "42",
    name: "Test Tube Holder",
    category: "Chemistry",
    info: [{ key: "1", price: "35.00", quantity: "1" }],
  },
  {
    key: "43",
    name: "Test Tube Brush",
    category: "Chemistry",
    info: [{ key: "1", price: "130.00", quantity: "12" }],
  },
  {
    key: "44",
    name: "Test Tube Stand",
    category: "Chemistry",
    info: [{ key: "1", price: "90.00", quantity: "1" }],
  },
  {
    key: "45",
    name: "Wash Bottle",
    category: "Chemistry",
    info: [{ key: "1", price: "85.00", quantity: "1" }],
  },
  {
    key: "46",
    name: "Kipps Apparatus",
    category: "Chemistry",
    info: [{ key: "1", price: "1300.00", quantity: "1" }],
  },
  {
    key: "47",
    name: "Water Trough",
    category: "Chemistry",
    info: [{ key: "1", price: "135.00", quantity: "1" }],
  },
  {
    key: "48",
    name: "Gas Jar With Lid",
    category: "Chemistry",
    info: [{ key: "1", price: "120.00", quantity: "Pair" }],
  },
  {
    key: "49",
    name: "Burette",
    category: "Chemistry",
    info: [{ key: "1", price: "395.00", quantity: "1" }],
  },
  {
    key: "50",
    name: "Pipette Stand",
    category: "Chemistry",
    info: [{ key: "1", size: "Circular", price: "605.00", quantity: "1" }],
  },
  {
    key: "51",
    name: "Conical Funnel",
    category: "Chemistry",
    info: [{ key: "1", price: "16.00", quantity: "1" }],
  },
  {
    key: "52",
    name: "Hand Glove",
    category: "Chemistry",
    info: [{ key: "1", price: "95.00", quantity: "Pair" }],
  },
  {
    key: "53",
    name: "Triangular File Handle",
    category: "Chemistry",
    info: [{ key: "1", price: "105.00", quantity: "1" }],
  },
  {
    key: "54",
    name: "Spatula",
    category: "Chemistry",
    info: [{ key: "1", price: "30.00", quantity: "1" }],
  },
  {
    key: "55",
    name: "China Dish Basin",
    category: "Chemistry",
    info: [{ key: "1", price: "70.00", quantity: "1" }],
  },
  {
    key: "56",
    name: "Morter and Peastle",
    category: "Chemistry",
    info: [{ key: "1", price: "160.00", quantity: "1" }],
  },
  {
    key: "57",
    name: "Bee Hive Self",
    category: "Chemistry",
    info: [{ key: "1", price: "80.00", quantity: "1" }],
  },
  {
    key: "58",
    name: "Copper Water Bath",
    category: "Chemistry",
    info: [{ key: "1", price: "505.00", quantity: "1" }],
  },
  {
    key: "59",
    name: "Atomic Model",
    category: "Chemistry",
    info: [
      { key: "1", size: "Big", price: "765.00", quantity: "1" },
      { key: "2", size: "Junior", price: "305.00", quantity: "1" },
    ],
  },
  {
    key: "60",
    name: "Centrifuge Machine Handling Table Top",
    category: "Chemistry",
    info: [{ key: "1", price: "1050.00", quantity: "1" }],
  },
  {
    key: "61",
    name: "Periodic Table",
    category: "Chemistry",
    info: [{ key: "1", size: "100x70", price: "155.00", quantity: "1" }],
  },
  {
    key: "62",
    name: "Valancy Chart",
    category: "Chemistry",
    info: [{ key: "1", size: "90x60", price: "195.00", quantity: "1" }],
  },
  {
    key: "63",
    name: "Chemistry Chart",
    category: "Chemistry",
    info: [{ key: "1", size: "90x60", price: "195.00", quantity: "1" }],
  },
  {
    key: "64",
    name: "Oven",
    category: "Chemistry",
    info: [{ key: "1", size: "12x12x12", price: "15500.00", quantity: "1" }],
  },
  {
    key: "65",
    name: "Centrifuge Machine",
    category: "Chemistry",
    info: [{ key: "1", price: "4500.00", quantity: "1" }],
  },
  {
    key: "66",
    name: "Magnetic Stirrer",
    category: "Chemistry",
    info: [{ key: "1", price: "3800.00", quantity: "1" }],
  },
  {
    key: "67",
    name: "Hitting Mental",
    category: "Chemistry",
    info: [{ key: "1", price: "2750.00", quantity: "1" }],
  },
  {
    key: "68",
    name: "Micrscope",
    category: "Biology",
    info: [
      { key: "1", size: "Medical", price: "6950.00", quantity: "1" },
      { key: "2", size: "Jr. Medical", price: "6100.00", quantity: "1" },
      { key: "3", size: "Standard", price: "5800.00", quantity: "1" },
      { key: "4", size: "Compound", price: "5050.00", quantity: "1" },
      { key: "5", size: "General", price: "4570.00", quantity: "1" },
    ],
  },
  {
    key: "69",
    name: "Microscope Single Nose",
    category: "Biology",
    info: [{ key: "1", price: "2575.00", quantity: "1" }],
  },
  {
    key: "70",
    name: "Dissecting Microscope",
    category: "Biology",
    info: [{ key: "1", price: "1790.00", quantity: "1" }],
  },
  {
    key: "71",
    name: "Bull Eye Microscope",
    category: "Biology",
    info: [{ key: "1", price: "2890.00", quantity: "1" }],
  },
  {
    key: "72",
    name: "Double Demonstration Eye Piece",
    category: "Biology",
    info: [{ key: "1", price: "1850.00", quantity: "1" }],
  },
  {
    key: "73",
    name: "Pointer Eye Piece",
    category: "Biology",
    info: [{ key: "1", price: "505.00", quantity: "1" }],
  },
  {
    key: "74",
    name: "Microscope Lens",
    category: "Biology",
    info: [{ key: "1", price: "1470.00", quantity: "Set of 3" }],
  },
  {
    key: "75",
    name: "Lense for Dissecting Microscope",
    category: "Biology",
    info: [{ key: "1", price: "370.00", quantity: "1" }],
  },
  {
    key: "76",
    name: "Mechanical Stage",
    category: "Biology",
    info: [{ key: "1", price: "1160.00", quantity: "1" }],
  },
  {
    key: "77",
    name: "Gnifying Hand Lens",
    category: "Biology",
    info: [{ key: "1", price: "220.00", quantity: "1" }],
  },
  {
    key: "78",
    name: "Dissecting Set in Bag",
    category: "Biology",
    info: [{ key: "1", price: "475.00", quantity: "1" }],
  },
  {
    key: "79",
    name: "Dissecting Tray with Wax",
    category: "Biology",
    info: [{ key: "1", price: "350.00", quantity: "1" }],
  },
  {
    key: "80",
    name: "Dissecting Tray without Wax",
    category: "Biology",
    info: [{ key: "1", price: "295.00", quantity: "1" }],
  },
  {
    key: "81",
    name: "Wax",
    category: "Biology",
    info: [{ key: "1", price: "270.00", quantity: "1 Kg" }],
  },
  {
    key: "82",
    name: "Dropping Bottle Tray Wooden",
    category: "Biology",
    info: [{ key: "1", price: "190.00", quantity: "1" }],
  },
  {
    key: "83",
    name: "Centrifuge Machine (Hand Driven table Top)",
    category: "Biology",
    info: [{ key: "1", price: "1050.00", quantity: "1" }],
  },
  {
    key: "84",
    name: "Centrifuge Machine(Electic)",
    category: "Biology",
    info: [{ key: "1", price: "4420.00", quantity: "1" }],
  },
  {
    key: "85",
    name: "Insulator",
    category: "Biology",
    info: [{ key: "1", size: "12x12x12", price: "15500.00", quantity: "1" }],
  },
  {
    key: "86",
    name: "Heating Mental",
    category: "Biology",
    info: [{ key: "1", price: "2750.00", quantity: "1" }],
  },
  {
    key: "87",
    name: "Museum Specimen",
    category: "Biology",
    info: [{ key: "1", price: "195.00", quantity: "1" }],
  },
  {
    key: "88",
    name: "Permanent Slide",
    category: "Biology",
    info: [
      { key: "1", size: "Common", price: "30.00", quantity: "1" },
      { key: "2", size: "Rear", price: "120", quantity: "1" },
    ],
  },
  {
    key: "89",
    name: "Slide Box",
    category: "Biology",
    info: [
      { key: "1", size: "25 Slides", price: "85.00", quantity: "1" },
      { key: "1", size: "50 Slides", price: "160.00", quantity: "1" },
    ],
  },
];
export default products;
